//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorAccount
    {
        public DoctorAccount()
        {
            this.PatBasicInfor = new HashSet<PatBasicInfor>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Hospital { get; set; }
    
        public virtual ICollection<PatBasicInfor> PatBasicInfor { get; set; }
    }
}
