//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    
    public partial class Exam
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string Result { get; set; }
        public string Note { get; set; }
    }
}
