//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LNCDDataModelContainer : DbContext
    {
        public LNCDDataModelContainer()
            : base("name=LNCDDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DoctorAccount> DoctorAccountSet { get; set; }
        public DbSet<PatBasicInfor> PatBasicInforSet { get; set; }
        public DbSet<PatPhysicalExam> PatPhysicalExamSet { get; set; }
        public DbSet<PatMMSE> PatMMSESet { get; set; }
        public DbSet<PatMoCA> PatMoCASet { get; set; }
        public DbSet<PatADL> PatADLSet { get; set; }
        public DbSet<PatOtherTest> PatOtherTestSet { get; set; }
        public DbSet<PatDisease> PatDiseaseSet { get; set; }
        public DbSet<VisitRecord> VisitRecordSet { get; set; }
        public DbSet<PatRecentDrug> PatRecentDrugSet { get; set; }
        public DbSet<PatLabExam> PatLabExamSet { get; set; }
        public DbSet<Drug> DrugSet { get; set; }
    }
}
