//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatLabExam
    {
        public PatLabExam()
        {
            this.Electrocardiogram = new Exam();
            this.Echocardiagraphy = new Exam();
            this.EEG = new Exam();
            this.CT = new Exam();
        }
    
        public int Id { get; set; }
        public string FT3 { get; set; }
        public string FT4 { get; set; }
        public string TT3 { get; set; }
        public string TT4 { get; set; }
        public string TSH { get; set; }
        public string Folacin { get; set; }
        public string B12 { get; set; }
        public string TBG { get; set; }
        public string EmptyG { get; set; }
        public string GAfter { get; set; }
        public string HbAlc { get; set; }
        public string UricAcid { get; set; }
        public string Cholesterol { get; set; }
        public string GanEster { get; set; }
        public string HDLC { get; set; }
        public string LDLC { get; set; }
        public string GOT { get; set; }
        public string GPT { get; set; }
        public string BUN { get; set; }
        public string CR { get; set; }
        public string Albumin { get; set; }
        public string RBC { get; set; }
        public string HB { get; set; }
        public string PLT { get; set; }
        public string WBC { get; set; }
        public string ApoE { get; set; }
        public string Protein { get; set; }
    
        public Exam Electrocardiogram { get; set; }
        public Exam Echocardiagraphy { get; set; }
        public Exam EEG { get; set; }
        public Exam CT { get; set; }
    
        public virtual VisitRecord VisitRecord { get; set; }
    }
}
