//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatMoCA
    {
        public int Id { get; set; }
        public string MC1 { get; set; }
        public string MC2 { get; set; }
        public string MC3 { get; set; }
        public string MC4 { get; set; }
        public string MC5 { get; set; }
        public string MC6 { get; set; }
        public string MC7 { get; set; }
        public string MC8 { get; set; }
        public string MC9 { get; set; }
        public string Total { get; set; }
    
        public virtual VisitRecord VisitRecord { get; set; }
    }
}
