//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatPhysicalExam
    {
        public PatPhysicalExam()
        {
            this.B1 = new BodyExam();
            this.B2 = new Exam();
            this.B3 = new Exam();
            this.B4 = new Exam();
            this.B5 = new Exam();
            this.B6 = new Exam();
            this.B7 = new Exam();
            this.B8 = new Exam();
            this.B9 = new Exam();
            this.B10 = new Exam();
            this.B11 = new Exam();
            this.B12 = new Exam();
            this.B12a = new Exam();
            this.B12b = new Exam();
            this.B12c = new Exam();
            this.B12d = new Exam();
            this.B12e = new Exam();
            this.B12f = new Exam();
        }
    
        public int Id { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Hipline { get; set; }
        public string BloodPressureH { get; set; }
        public string BloddPressureL { get; set; }
    
        public BodyExam B1 { get; set; }
        public Exam B2 { get; set; }
        public Exam B3 { get; set; }
        public Exam B4 { get; set; }
        public Exam B5 { get; set; }
        public Exam B6 { get; set; }
        public Exam B7 { get; set; }
        public Exam B8 { get; set; }
        public Exam B9 { get; set; }
        public Exam B10 { get; set; }
        public Exam B11 { get; set; }
        public Exam B12 { get; set; }
        public Exam B12a { get; set; }
        public Exam B12b { get; set; }
        public Exam B12c { get; set; }
        public Exam B12d { get; set; }
        public Exam B12e { get; set; }
        public Exam B12f { get; set; }
    
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
}
